version: "3.1"

services:
  db:
    image: postgres
    container_name: db_ovitrap
    restart: always
    ports:
      - ${LOCAL_DB_PORT}:5432
    environment:
      POSTGRES_DB: ${LOCAL_DB_NAME}
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASS}
  api:
    build: .    
    container_name: api_ovitrap
    restart: always
    depends_on: 
      - db
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${LOCAL_API_PORT}:${LOCAL_API_PORT}
    command: npm run dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
